version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout:
          path: igseqhelper
      - restore_cache:
          keys:
            - cache-{{ checksum "igseqhelper/inst/environment.yml" }}
      - run:
          name: Install
          command: |
            if [[ ! -e ~/miniconda3/envs/igseqhelper ]]; then
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
              bash Miniconda3-latest-Linux-x86_64.sh -b
              ~/miniconda3/bin/conda install -c conda-forge mamba --quiet
              ~/miniconda3/bin/mamba env update --file igseqhelper/inst/environment.yml --quiet
            fi
          no_output_timeout: 20m
      - save_cache:
          paths: [ ~/miniconda3 ]
          key: cache-{{ checksum "igseqhelper/inst/environment.yml" }}
      - run:
          name: Test python package
          command: |
            cd igseqhelper/inst/python
            source ~/miniconda3/bin/activate igseqhelper
            python -m unittest
