version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "inst/environment.yml" }}
      - run:
        name: install
        command: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda3-latest-Linux-x86_64.sh -b
          ~/miniconda3/bin/conda update --file inst/environment.yml
      - save_cache:
          paths: [ ~/miniconda3 ]
          key: cache-{{ checksum "inst/environment.yml" }}
