# conda environment definition file for igseq
name: igseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - clustalw
  - pear
  - seqmagick
  - snakemake
  - vsearch
  - cutadapt
  # requirements for IgDiscover
  - igdiscover
  # requirements for pRESTO
  - pip
  - numpy>=1.8
  - scipy>=0.14
  - pandas>=0.15
  - biopython>=1.65
  - pip:
    - presto
