# conda environment YAML for igseqhelper
name: igseqhelper
channels:
  - ShawHahnLab
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # general
  - snakemake>=6.8.0
  - seqmagick>=0.8.4
  - fastqc>=0.11.9
  - fasttree>=2.1.11
  # igseq
  - igseq>=0.3.0
