# conda environment YAML for igseqhelper
name: igseqhelper
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # general
  - snakemake>=6.8.0
  - seqmagick>=0.8.4
  - igblast>=1.17.1
  # igseq
  - biopython>=1.79
  - python>=3.9.7
  - bwa>=0.7.17
  - samtools>=1.13
  - cutadapt>=3.5
  - pear>=0.9.6
  - igblast>=1.17.1
  - pip
  - pip:
    - git+https://github.com/ShawHahnLab/igseq.git
