# conda environment definition file for igseq
name: igseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - clustalw
  - pear
  - seqmagick
  - snakemake>=5.9.1
  - vsearch
  - cutadapt
  - rpy2
  - imagemagick
  - igblast
  - bwa
  - samtools
  # Utils
  - seqtk
  # For R package
  - r-devtools
  - r-ggplot2
  - r-dplyr
  - r-reshape2
  - r-upsetr
  - r-rmarkdown
  - r-kableextra
  - r-magick
  - r-pheatmap
  - bioconductor-biostrings
  # requirements for IgDiscover
  - igdiscover
  - r-rjson # helps parse outputs
  # requirements for pRESTO
  - pip
  - numpy>=1.8
  - scipy>=0.14
  - pandas>=0.15
  - biopython>=1.65
  - pip:
    - presto
  # Not essential but should allow manually running SONAR's Python and R
  # scripts
  - airr
  - docopt
  - r-docopt
