# Antibody Lineage Summaries

```{r}
#### These helpers should move to the R package eventually, but keeping here for now

# Load my own SONAR ID/DIV summary data from the various per-sample and 
# per-chain files.  If only one of heavy/light is found that one is included. 
# If neither is found, this returns NULL.
load_island_stats <- function(lineage, metadata, root=ROOT) {
  chunks <- lapply(c("heavy", "light"), function(chain) {
    lineage_attrs <- subset(metadata$antibody_lineages, AntibodyLineage == lineage)
    subject <- lineage_attrs$Subject
    vl <- subset(metadata$antibody_lineages, AntibodyLineage == lineage)$VL
    chain_type <- if (chain == "heavy") {
      "gamma"
    } else if (chain == "light") {
      if (grepl("^IGLV", vl)) {
        "lambda"
      } else {
        "kappa"
      }
    }
    # select specimens matching chain and chain type
    specimens <- subset(metadata$samples, Chain == chain & Type == chain_type)$Specimen
    # select specimens matching subject
    specimens <- subset(metadata$specimens, Specimen %in% specimens & Subject == subject)$Specimen
    # and cell type
    specimens <- subset(metadata$specimens, Specimen %in% specimens & grepl("IgG", CellType))$Specimen
    result <- do.call(rbind, lapply(file.path(
      root,
      "analysis/reporting/by-lineage",
      lineage,
      paste(
        specimens, chain, chain_type, sep = "."),
      "island_stats.csv"), function(fp) {
        if (file.exists(fp)) {
         x <- read.csv(fp, stringsAsFactors = FALSE)
         x$Chain <- rep(chain, nrow(x))
         x$Type <- rep(chain_type, nrow(x))
          if (nrow(x)) {
            x
          } 
        }
      }))
    if (! is.null(result)) {
      result <- result[order(result$timepoint, result$specimen), ]  
    }
    result
  })
  chunks <- chunks[! sapply(chunks, is.null)]
  if (length(chunks)) {
    if (length(chunks) > 1) {
       for (cname in colnames(chunks[[1]])) {
        if (! cname %in% colnames(chunks[[2]])) {
          chunks[[2]][[cname]] <- NA
        }
      }
      for (cname in colnames(chunks[[2]])) {
        if (! cname %in% colnames(chunks[[1]])) {
          chunks[[1]][[cname]] <- NA
        }
      } 
    }
    result <- do.call(rbind, chunks)
  } else {
    result <- NULL
  }
  result
}

# Draw a pair (if both chains are given) of scatterplots summarizing
# identity/divergence across timepoints.
plot_island_stats <- function(island_stats) {
  # the earliest timepoints will tend to have the closest clustering and
  # probably fewer points, so we'll order the data frame so ggplot2 draws those
  # points last (and on top of points drawn earlier) so they're less likely to
  # be hidden by re-occurrences in later timepoints.
  island_stats <- island_stats[order(-island_stats$timepoint), ]
  plt <- ggplot(
    island_stats,
    aes(
      x = germ_div,
      y = ab_id_median,
      col = factor(timepoint),
      size = log10(cluster_count),
      alpha = 0.6)) +
    scale_alpha_identity() +
    geom_point()
  if ("Chain" %in% names(island_stats)) {
    plt <- plt + facet_grid(Chain ~ .)
  }
    
  plt <- plt +
    coord_cartesian(
      xlim = c(0, max(island_stats$germ_div)),
      ylim = c(min(island_stats$ab_id_median), 100)) +
    scale_size_area() +
    labs(x = "% Divergence from germline V", y = "Median % identity to all antibodies") +
    guides(
      col=guide_legend(title="Timepoint (weeks)"),
      size=guide_legend(title="Log10 Sequences")) +
    theme_bw()
  plt
}

```

```{r results="asis"}
# TODO
# make sections on a per-subject-and-lineage basis, summarizing all the
# information we have from IgDiscover for germline and SONAR for longitudinal.
# stack AA alignments annotated by framework/cdr across timepoints and including
# mature and germline.

for (idx in 1:nrow(metadata$antibody_lineages)) {
  subject <- metadata$antibody_lineages$Subject[idx]
  lineage <- metadata$antibody_lineages$AntibodyLineage[idx]
  if (sum(metadata$antibody_lineages$Subject == subject) == 1 && subject == lineage) {
    cat(paste0("## ", subject, "\n\n"))  
  } else {
    cat(paste0("## ", subject, " - ", lineage, "\n\n"))
  }
  isolates <- subset(metadata$antibody_isolates, AntibodyLineage == lineage)
  seqids <- with(metadata$antibody_lineages, list(
    heavy = c(V=VH[idx], D=DH[idx], J=JH[idx]),
    light = c(V=VL[idx], J=JL[idx])))
  has_alleles <- all(unlist(seqids) != "")
  # if (has_alleles) {
  #   seqs <- load_alleles_for_subject(seqids, subject)
  # }
  island_stats <- load_island_stats(lineage, metadata)
  if (! is.null(island_stats)) {
    plot(plot_island_stats(island_stats) + ggtitle(lineage))
  }
}
```